// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd2dkdfeO51LTk7wkLhEnQeUQXzTIEr2Q',
    appId: '1:369754342006:web:65ba829e8ffe3fda351557',
    messagingSenderId: '369754342006',
    projectId: 'test-module-app-3abc7',
    authDomain: 'test-module-app-3abc7.firebaseapp.com',
    storageBucket: 'test-module-app-3abc7.appspot.com',
    measurementId: 'G-LFGH081V2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUTxYDXLhcPgNOFgOGNpoIq8mJQSXlDYc',
    appId: '1:369754342006:android:a1838096859313dc351557',
    messagingSenderId: '369754342006',
    projectId: 'test-module-app-3abc7',
    storageBucket: 'test-module-app-3abc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUydcdFS3So6AlESsqagIFD0l73ARrLqs',
    appId: '1:369754342006:ios:c291c3df155ab1e4351557',
    messagingSenderId: '369754342006',
    projectId: 'test-module-app-3abc7',
    storageBucket: 'test-module-app-3abc7.appspot.com',
    iosBundleId: 'com.example.safaricomDarajaModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUydcdFS3So6AlESsqagIFD0l73ARrLqs',
    appId: '1:369754342006:ios:59c972aca352fd47351557',
    messagingSenderId: '369754342006',
    projectId: 'test-module-app-3abc7',
    storageBucket: 'test-module-app-3abc7.appspot.com',
    iosBundleId: 'com.example.safaricomDarajaModule.RunnerTests',
  );
}
